---
- name: Get OS type
  debug:
    var: ansible_facts.distribution
#.ansible_distribution 

- name: Update repositories cache and install  package
  apt:
    name: python-pip
    update_cache: yes
  when: ansible_facts.distribution=='Ubuntu'


- name: Package to remove
  pip:
    name: docker-py
    state: absent
- name: Package to install
  pip:
    name: docker
